### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by adeelejaz** [jonstipe/number-polyfill#6]
Hi,

Just thought if you would be interested in dropping jQuery from the plugin? I believe it will really open up this plugin for people who do not use it because it depends on jQuery. I'd love to lend a hand in having a go at it.

Thanks.

**Comment by jonstipe** [comment]
I suppose it's possible, but some parts would probably be harder to do without jQuery's assistance and would probably result in a larger file size. I don't think the dependency will really stop that many people from using it.

**Comment by adeelejaz** [comment]
I agree dependency won't stop people from using it but people who want to use the polyfill will have to include jQuery. It's orrite if one is already using it on the website but it not, they would have include it.

Just as an idea, how about two versions? One for jQuery, the other without? Just a thought...

**Comment by jonstipe** [comment]
I just don't know if there's really that much demand for a standalone version since jQuery is already in such common use anyway. I don't know if that many people would be so opposed to including jQuery that they won't want to use the polyfill just because of that. But hey, you can do what you want, I guess.
